const data = {
    products: [
        {
            _id: '1',
            name: 'Nike Slim Shirt',
            category: 'Shirts',
            image: '/images/p1.jpg',
            price: 120,
            brand: 'Nike',
            rating: 2.5,
            numReviews: 10,
            description: 'hugh quality product',
        },
        {
            _id: '2',
            name: 'Adidas Fit Shirt',
            category: 'Shirts',
            image: '/images/p2.jpg',
            price: 100,
            brand: 'Adidas',
            rating: 4.0,
            numReviews: 10,
            description: 'hugh quality product',
        },
        {
            _id: '3',
            name: 'Lacosta Free Shirt',
            category: 'Shirts',
            image: '/images/p3.jpg',
            price: 220,
            brand: 'Lacoste',
            rating: 4.8,
            numReviews: 17,
            description: 'hugh quality product',
        },
        {
            _id: '4',
            name: 'Nike Slim Pants',
            category: 'Pants',
            image: '/images/p4.jpg',
            price: 40,
            brand: 'Nike',
            rating: 3.5,
            numReviews: 20,
            description: 'hugh quality product',
        },
        {
            _id: '5',
            name: 'Puma Slim Pant',
            category: 'Pants',
            image: '/images/p5.jpg',
            price: 150,
            brand: 'Puma',
            rating: 4.0,
            numReviews: 22,
            description: 'hugh quality product',
        },
        {
            _id: '6',
            name: 'Adidas Fit Pant',
            category: 'Pants',
            image: '/images/p6.jpg',
            price: 220,
            brand: 'Adidas',
            rating: 4.5,
            numReviews: 10,
            description: 'hugh quality product',
        },
    ],
};
export default data;